name: Build Test

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build Test
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22.19"
          cache: "npm"

      - name: Install Bun
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun i

      - name: Build application
        run: bun bake

      - name: Check build artifacts
        run: |
          test -f dist/index.html
          test -d dist/ui
          test -f dist/ui/editor-*.js
          test -f dist/ui/stylez-*.css
          echo "Build successful"
